//go:build integration

package postgres

import (
	"context"
	"net"
	"net/url"
	"strconv"
	"strings"
	"testing"

	"db-sync/internal/model"
	"db-sync/internal/schema"
	"db-sync/internal/testkit"

	"github.com/jackc/pgx/v5"
)

func TestPostgresDiscoverSchema(t *testing.T) {
	ctx := context.Background()
	container := testkit.StartPostgresContainer(ctx, t)
	defer container.Cleanup()
	dsn := strings.ReplaceAll(container.DSN, "${PG_PASSWORD}", "app-secret")
	seedPostgresSchema(ctx, t, dsn)

	adapter := NewAdapter()
	snapshot, err := adapter.DiscoverSourceSchema(ctx, dsn, model.EnginePostgres)
	if err != nil {
		t.Fatalf("DiscoverSourceSchema() error = %v", err)
	}
	orders := mustFindTable(t, snapshot, "app.orders")
	if len(orders.Columns) != 3 {
		t.Fatalf("orders columns = %d, want 3", len(orders.Columns))
	}
	if orders.Columns[0].Name != "id" || orders.Columns[1].Name != "account_id" || orders.Columns[2].Name != "created_at" {
		t.Fatalf("unexpected column order: %+v", orders.Columns)
	}
	if len(orders.ForeignKeys) != 1 {
		t.Fatalf("orders foreign keys = %d, want 1", len(orders.ForeignKeys))
	}
	if got := orders.ForeignKeys[0].ReferencedTable.String(); got != "public.accounts" {
		t.Fatalf("referenced table = %q, want public.accounts", got)
	}
}

func TestPostgresDiscoverSchemaBlockedMetadata(t *testing.T) {
	ctx := context.Background()
	container := testkit.StartPostgresContainer(ctx, t)
	defer container.Cleanup()
	dsn := strings.ReplaceAll(container.DSN, "${PG_PASSWORD}", "app-secret")
	seedPostgresSchema(ctx, t, dsn)
	restricted := postgresRestrictedDSN(t, ctx, dsn)

	adapter := NewAdapter()
	if _, err := adapter.DiscoverSourceSchema(ctx, restricted, model.EnginePostgres); err == nil {
		t.Fatal("DiscoverSourceSchema() error = nil, want blocked metadata error")
	}
}

func seedPostgresSchema(ctx context.Context, t *testing.T, dsn string) {
	t.Helper()
	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		t.Fatalf("pgx.Connect() error = %v", err)
	}
	defer conn.Close(ctx)
	statements := []string{
		"create schema if not exists app",
		"create table if not exists public.accounts (id bigint generated by default as identity primary key, email text not null)",
		"create table if not exists app.orders (id bigint generated by default as identity primary key, account_id bigint not null references public.accounts(id), created_at timestamptz not null default now())",
		"create role limited login password 'limited-secret'",
		"grant connect on database app to limited",
		"grant usage on schema public, app to limited",
	}
	for _, statement := range statements {
		if _, err := conn.Exec(ctx, statement); err != nil && !strings.Contains(err.Error(), "already exists") {
			t.Fatalf("Exec(%q) error = %v", statement, err)
		}
	}
	if _, err := conn.Exec(ctx, "revoke all privileges on all tables in schema public, app from limited"); err != nil {
		t.Fatalf("revoke limited privileges error = %v", err)
	}
}

func postgresRestrictedDSN(t *testing.T, ctx context.Context, dsn string) string {
	t.Helper()
	parsed, err := url.Parse(dsn)
	if err != nil {
		t.Fatalf("url.Parse(%q) error = %v", dsn, err)
	}
	host, portText, err := net.SplitHostPort(parsed.Host)
	if err != nil {
		t.Fatalf("SplitHostPort(%q) error = %v", parsed.Host, err)
	}
	port, err := strconv.Atoi(portText)
	if err != nil {
		t.Fatalf("Atoi(%q) error = %v", portText, err)
	}
	return (&url.URL{Scheme: "postgres", User: url.UserPassword("limited", "limited-secret"), Host: net.JoinHostPort(host, strconv.Itoa(port)), Path: "/app", RawQuery: "sslmode=disable"}).String()
}

func mustFindTable(t *testing.T, snapshot schema.Snapshot, tableID string) schema.Table {
	t.Helper()
	table, ok := snapshot.TableByID(schema.ParseTableID(tableID))
	if !ok {
		t.Fatalf("table %q not found in snapshot", tableID)
	}
	return table
}
